### ISSUE TITLE
[Bug] gtk-update-icon-cache fails in Arch Linux git installer

### ISSUE THREAD

**Issue by btd1337** [keeferrourke/la-capitaine-icon-theme#27]
![screenshot from 2016-08-13 15-14-51](https://cloud.githubusercontent.com/assets/11943860/17644842/e56a0dfa-6168-11e6-82b5-29b9fb05e7e5.png)

**Comment by keeferrourke** [comment]
I don't maintain the Arch package, and I don't work with an icon-cache.

I do however acknowledge that running 

    gtk-update-icon-cache ~/.icons/la-capitaine-icon-theme

spits out that very unhelpful error however. Does anyone have any ideas what would cause it?

**Comment by keeferrourke** [comment]
This was an issue back at #1 @viewizard had said it was resolved with his Gentoo ebuild; but I suppose the issue has resurfaced. Any ideas?

**Comment by viewizard** [comment]
I don't have any issues with version 0.2.1 on Gentoo with gtk-update-icon-cache. I hecked it one more time - no errors during gtk-update-icon-cache execution.

**Comment by auroszx** [comment]
I didn't have this issue before, I was at `37914c1` and cache was generated succesfully. Decided to pull the latest commits and fast forwarded to `96b856f`. Then, I tried to update the cache and failed as described by the original post. I tried deleting the current cache and updating it again, still failed.

I'm on Debian Stretch/Testing, up to date. Maybe this is related to one of the commits in between the two I previously mentioned.

**Comment by keeferrourke** [comment]
Currently out of country, but when I get a chance I'll investigate.

**Comment by viewizard** [comment]
Faced with this issue in version 0.3.0.
"apps/symbolic/accessories-text-editor-symbolic (copy).svg" should be removed (or renamed) to solve the issue.

**Comment by auroszx** [comment]
Can confirm, deleted the file mentioned by @viewizard and cache was generated successfully.

**Comment by keeferrourke** [comment]
@viewizard @auroszx I must have accidentally pushed that; fixed in https://github.com/keeferrourke/la-capitaine-icon-theme/commit/e3602956b5061658f733210c3023bd8accf9d385.

Cached should generate properly now.

**Comment by keeferrourke** [comment]
Tested, closing.
